json.extract! @item,
              :id,
              :full_name,
              :brand,
              :sku,
              :category_1,
              :product_code,
              :in_stock,
              :details,
              :sizes,
              :color,
              :price,
              :washing_instructions,
              :materials,
              :photo_urls,
              :product_url,
              :created_at,
              :updated_at
